### PR TITLE
Update log capabilities

### PR DESCRIPTION
**Pull request by BlueRaja**
Logs can now use `String.Format()` syntax.  Also, added ability to turn off bot name in logs.

### CODE REVIEW

**Comment by BlueRaja** [comment]
@WildCard65 

    GetUserHandler(new SteamID((ulong)0)).OnBotCreated();

This line is causing the bot to crash, because the bot is being created without a valid SteamID.  Why was it added?

**Comment by WildCard65** [comment]
Odd, it worked fine for me(After changing a line in userhandler to make it work)

**Comment by BlueRaja** [comment]
It causes the bot constructor to be called with an invalid `SteamID`.  What the purpose of that?

**Comment by WildCard65** [comment]
Because the bot hasn't logged in so it has no valid steamid I can pass to it so NULL_STEAMID is to satisfy GetUserHandler

**Comment by WildCard65** [comment]
@BlueRaja When can this be merged?

**Comment by BlueRaja** [comment]
This still has the breaking change that the constructor is called with a null SteamID.

**Comment by WildCard65** [comment]
Is it possible for a static virtual method?

**Comment by BlueRaja** [comment]
There's no such thing as a static virtual method

**Comment by WildCard65** [comment]
Ya, read that, ok plan B that will work(And bypasses constructor): Custom
attribute on a static method, reflection

**Comment by BlueRaja** [comment]
I don't think that's a good solution either.

We should just get rid of OnBotCreated() altogether.  If there's any sort of customization of the logs we want, that should be in the config file.

**Comment by WildCard65** [comment]
Ok, a config option can work too.

**Comment by WildCard65** [comment]
Ok, made another PR that makes bot owners choose what loggers they want.

**Comment by WildCard65** [comment]
Ok update status on PR I made. Once this is merged, it's going to be re-opened onto master instead of this PR just for discussion.

**Comment by BlueRaja** [comment]
Created #721

**Pull request closed without merging**
