### PR TITLE
Added the ability to change Accept-Language header in SteamKit's HTTP requests.

### PR DESCRIPTION
**Pull request by fjch1997**

### CODE REVIEW

**Comment by scholtzm** [comment]
You make your PRs super hard to review, since they all contain changes from one another.

**Comment by fjch1997** [comment]
It's also super hard for me to rebase to the SteamKit 1.6 version of SteamBot.

If somebody can kindly merge #1009 on which my today's PRs are based into master, it will save a lot of trouble

**Comment by fjch1997** [comment]
reverted irrelevant commits

**Comment by BlueRaja** [comment]
Don't revert commits, that will cause merge conflicts when the other changes are pushed.  Rebase + force-push instead

**Comment by fjch1997** [comment]
#1015

**Pull request closed without merging**
