### PR TITLE
Modular logging.

### PR DESCRIPTION
**Pull request by WildCard65**
100% Configurable, 100% Extendable, 100% broken config backwards compatibility.

Note: VS modified the formatting of the json file.

### CODE REVIEW

**Comment by WildCard65** [comment]
@BlueRaja this is now in a lot less commits

**Comment by scholtzm** [comment]
Wouldn't it be better to perhaps use a 3rd party logging library e.g. log4net?

**Comment by WildCard65** [comment]
Depends on how well we can implement it with how we do our configuration

**Comment by WildCard65** [comment]
@BlueRaja mind reviewing this?

**Comment by WildCard65** [comment]
@scholtzm I don't think it'll be easy to implement log4net into SteamBot

**Comment by scholtzm** [comment]
Yeah I suppose it would be a pretty big change in this case.

**Comment by WildCard65** [comment]
@BlueRaja Is this mergable?

**Comment by BlueRaja** [comment]
I'm not clear on what "100% broken compatibility" means.  What breaking changes have been made?  What changes would existing clients need to make to fix their bots?

**Comment by WildCard65** [comment]
So far the only place it's broken is configuration as it modifies the
configuration to allow custom loggers to be easily loaded into the bot.
Settings template has 2 default loggers in as examples

**Comment by WildCard65** [comment]
@BlueRaja So what about this PR?

**Comment by BlueRaja** [comment]
How do others feel about this?

**Comment by Bottswana** [comment]
If I'm completely honest I don't see this being needed. I'm not against it but it's a lot for something I wouldn't use at least.

**Comment by WildCard65** [comment]
Well it opens possibilities of custom loggers.

**Comment by Bottswana** [comment]
I know what it does, I just don't see it as entirely necessary.

**Pull request closed without merging**
