### PR TITLE
Update log capabilities

### PR DESCRIPTION
**Pull request by BlueRaja**
Recreating #617 to not include the extensible logging stuff, so we can get this merged already.

Could someone please test?

### CODE REVIEW

**Comment by WildCard65** [comment]
@BlueRaja I think this is ok just to merge as it works quite well(Was testing it when it had my Modular Logging stuff in)

**Comment by BlueRaja** [comment]
Anyone else wanna test out this beast before it gets merged?

**Comment by WildCard65** [comment]
Calling @Bottswana @scholtzm @FrozenHaxor to this

**Comment by scholtzm** [comment]
I remember code reviewing this long time ago and it looked good to me.

**Comment by Bottswana** [comment]
Yup, tested this version OK from me

**Comment by FrozenHaxor** [comment]
This is good to go.

**Pull request merged**
