### PR TITLE
dev-2016

### PR DESCRIPTION
**Pull request by KAMAELUA**

### CODE REVIEW

**Comment by RafalNiewinski** [comment]
What's this ?

**Comment by BlueRaja** [comment]
```private String apiUrl = "http://localhost/yii2/bets/webtask.php"; ```

I'm assuming this was not meant to be a PR?

**Comment by scholtzm** [comment]
Doesn't look like trying to comply with Valve's ToS either. 😄

**Comment by KAMAELUA** [comment]
Oh, sorry, I missclick somewhere when try to update my fork.

**Pull request closed without merging**
