### PR TITLE
Update the SteamAuth package to the latest NuGet Version

### PR DESCRIPTION
**Pull request by nightfuryninja**
I update the SteamAuth NuGet package to the latest one that Geel9 released 17 days ago. I never got around to updating the packages required within the actual GitHub SteamBot. So here it is, the latest required packages have all been updated to version 2.0.0. Could someone just check and merge this for me if it is all in order?

### CODE REVIEW

**Comment by BlueRaja** [comment]
Can anyone check this?

**Comment by ThereWasADream** [comment]
No immediate issues. If you don't see another comment from me it means I continued to have no issues.

-Narth

**Comment by greggameplayer** [comment]
@nightfuryninja There is some issue with this SteamAuth version because visual studio express 2013 can't find the steamauth, but the steamauth is downloaded on correct location. so I can't compile

**Comment by nightfuryninja** [comment]
Yeah, I am having that issue currently with Visual Studio 2017 edition. Give me a few moments and I will try to find a fix. (Sorry for the inconvenience this has caused).

**Pull request merged**
