### PR TITLE
Upgrade to SteamKit 1.7.

### PR DESCRIPTION
**Pull request by fjch1997**
#777 

This seems to be good but Github isn't showing the additions and deletions correctly. The only change i made was removing HandleSteamMessage and moving them to BackgroundWorkerOnDoWork with CallbackManager. If i click Compare with Previous Version in Visual Studio, the changes are shown as expected.

### CODE REVIEW

**Comment by BlueRaja** [comment]
Github is correct, you are branching off the wrong version.  Branch off of `Jessecar96:master` explicitly and remake the changes.

**Comment by fjch1997** [comment]
@BlueRaja My branch is from the latest, that i can be sure. And if I make visual studio showing the difference, it's clean and correct. It's just Github isn't showing it in the right way.

**Comment by BlueRaja** [comment]
https://github.com/Jessecar96/SteamBot/commit/961c6a2faf671832f69117bfcd0123189421f490

When I pull down your branch and look at the commits, I see the same thing.

**Comment by fjch1997** [comment]
OK..... I'll try to delete the branch and do this once again

**Comment by fjch1997** [comment]
Github must be kidding me... This time i was editing directly from the web interface and the results are the same.

**Comment by fjch1997** [comment]
#1009

**Pull request closed without merging**
