### PR TITLE
Steam bot unit test

### PR DESCRIPTION
**Pull request by WildCard65**
Ok, in order for appveyor to run this. @Jessecar96 needs to set appveyor to build the solution this PR adds.

### CODE REVIEW

**Comment by BlueRaja** [comment]
Note that the unit tests are in a separate solution, so that normal SteamBot users won't have to download nUnit as a dependency.

I approve!  *(But I haven't tested it myself yet)*

**Comment by WildCard65** [comment]
Build failed with appveyor with, "Specify which project or solution file to use because the folder contains more than one project or solution file." which is to be expected. It does build and tests do run. Only downside is that is depends on NuGet.exe being present in the .nuget folder which I believe AppVeyor does automatically during build.

**Comment by WildCard65** [comment]
Ok, need to fix test script.

**Comment by WildCard65** [comment]
Ok, after some testing, I discovered AppVeyor has auto detection for NUnit tests. Results of that here: https://ci.appveyor.com/project/WildCard65/steambot/build/1.0.12/tests

**Comment by WildCard65** [comment]
@scholtzm @Bottswana Your opinion?

**Comment by scholtzm** [comment]
I like the tests very much. Combining these with CI is even better. :+1: from me.

**Comment by Bottswana** [comment]
Looks like a great idea to be honest.

**Comment by FrozenHaxor** [comment]
Yup, this would make the life easier.

**Comment by Jessecar96** [comment]
Yay got it to build and test.
Although that lowercase f in Tf2Value still annoys me.

**Comment by scholtzm** [comment]
@Jessecar96 [He didn't listen!](https://github.com/Jessecar96/SteamBot/pull/694#issuecomment-69750283) :smile:

**Comment by Jessecar96** [comment]
That's gonna annoy me forever now

**Comment by BlueRaja** [comment]
Given that it was just merged 2 days ago, there's still time to rename it without breaking tons of existing bots.  Since my opinion is outnumbered, I'd be fine with someone changing it.

**Comment by BlueRaja** [comment]
#725

**Pull request merged**
