### PR TITLE
Edited SteamWeb class

### PR DESCRIPTION
**Pull request by igeligel**
# What i have done

I improved the functionality of the DoLogin(string username, string password) method. I needed this earlier and fixed it by adding some headers. Also this method is really important if you want to login to some third-party-sites because you need to do the login and then go to the open id verification. So i decided to improve it.

# What i have used
C# convention are from this site: https://msdn.microsoft.com/en-gb/library/ff926074.aspx
resharper can be found here: https://www.jetbrains.com/resharper/
I have used resharper version: 9.1.3

### CODE REVIEW

**Comment by scholtzm** [comment]
> Also this method is really important if you want to login to some third-party-sites because you need to do the login and then go to the open id verification.

You don't need `DoLogin` for this.

**Comment by igeligel** [comment]
> You don't need DoLogin for this.

Ok, have not tried with Authenticate method yet. Still wanted to update. If you do not merge i have no problem with that. But what make me cautious that the AppVeyor build failed.

> SteamWeb.cs(91,17): error CS1056: Unexpected character '$' [C:\projects\steambot\SteamTrade\SteamTrade.csproj]

Should be fine if you work with C# 6 and VS 2015.

**Comment by BlueRaja** [comment]
1. I disagree with a lot of the style changes made.  The _"use `var` for everything"_ choice that Resharper makes is widely disagreed with.  Also most style-guides use braces even for one-line blocks - I believe that's the default in Resharper too?

2. It's impossible to code-review a PR when you group large refactorings and small functional changes into the same commit.  Please separate the refactorings into separate commits.

3. To use C# 6 features you need to update the .csproj file.  Appveyor is correct that this PR doesn't compile.

4. Thank you for the documentation comments!  They're very helpful, I wish we had more of them around the codebase.

**Comment by igeligel** [comment]
* Ok i will rework the Pull request. And resharper's goal is to reduce nesting like:
```
if (!isGetMethod && !String.IsNullOrEmpty(dataString))
{
    // Code goes here
    byte[] dataBytes = Encoding.UTF8.GetBytes(dataString);
    request.ContentLength = dataBytes.Length;
    using (Stream requestStream = request.GetRequestStream())
    {
        requestStream.Write(dataBytes, 0, dataBytes.Length);
    }
}
```
Will transform into:
```
if (isGetMethod || string.IsNullOrEmpty(dataString)) return request.GetResponse() as HttpWebResponse;
// Code goes here
byte[] dataBytes = Encoding.UTF8.GetBytes(dataString);
request.ContentLength = dataBytes.Length;
using (Stream requestStream = request.GetRequestStream())
{
    requestStream.Write(dataBytes, 0, dataBytes.Length);
}
```

And it is the standard in resharper that for single-line-if-statements no braces are needed:
[Stackoverflow Thread](http://stackoverflow.com/questions/3622236/resharper-force-curly-braces-around-single-line)

* Ok, i will change the pull and create more commits.

* Ok, just use an older version i guess.

* How I'd say: I will create another pull or edit this one with more commits and specific changes, probably more documentation about other methods.

**Pull request closed without merging**
