### PR TITLE
Steam Auth empty 

### PR DESCRIPTION
**Pull request by GreYzZ**
If I download the zip the SteamAuth folder is empty

### CODE REVIEW

**Comment by scholtzm** [comment]
I don't think you wanted (or want) to do this. :grinning:

**Comment by Jessecar96** [comment]
um what

**Comment by GreYzZ** [comment]
@Jessecar96 
Yes if I download the zip there is nothing in the folder

**Comment by Jessecar96** [comment]
@GreYzZ You made a bad pull request, that's probably not what you wanted to do.

**Pull request closed without merging**
