### PR TITLE
Add new callback for email confirmations

### PR DESCRIPTION
**Pull request by BlueRaja**
Extended #732 to include email confirmation callback

### CODE REVIEW

**Comment by scholtzm** [comment]
Looks good. The only thing that pisses me off that status 6 also happens when both users have the e-mail confirmations disabled. However, it's not something we can do much about.

**Comment by BlueRaja** [comment]
Yeah, I don't know what we can do about that other than ask users to handle it in their UserHandler.

**Comment by radiumx3** [comment]
ETA ??  @BlueRaja

**Comment by ThereWasADream** [comment]
We're all volunteers bro. Open source means everyone who uses the code helps update and debug it.

My vote is that it's good, other than the annoying fact that when Steam's servers are crap, I need to keep the bot checking for the trade offer until it completes. Still writing that catch, actually.

**Comment by BlueRaja** [comment]
I've just been waiting for someone other than me to confirm they actually tested it :) I'll merge this now.

**Pull request merged**
