### PR TITLE
Compatilibity with SHA1 Sentry file

### PR DESCRIPTION
**Pull request by GAMELASTER**
Automatic detect, use, update... and mainly, its works :dancer: 
Eh i almost forgot, just only paste a sentryfile from NodeSteam to sentryfiles (format sentry_USERNAME.hash"), its automatically detects. I though this is a best way to do that.

Now, its be works to merge pull request + on #667 is not added a Updating a sentry file, i though its good to updating a Sentry file what is using, not creating new etc..

P.S. Sorry for wrong tabbing, i edited it from Notepad++, not Visual Studio so its do a wrong tabbing :D

### CODE REVIEW

**Comment by scholtzm** [comment]
1. node-steam provides complete sentry blob since v1.x, not just the SHA-1
2. your code seems to only allow files that are named "sentry_{0}.hash" (where {0} is the login)

Frankly, this is no longer needed.

**Comment by GAMELASTER** [comment]
@scholtzm Yes, huh, i already using a not v1.x version and this tweak is for me great. Anyway i though its be a good to still have this feature, maybe i do another comit what add a type of sentry file to config, when default is a nonSHA1 sentry

**Comment by scholtzm** [comment]
This patch would make sense before but it's long over due.

`node-steam` doesn't store the sentry file in any particular fashion, it just provides the complete buffer since v1.x. This buffer is identical to SteamBot's format. Adding support for legacy versions of `node-steam` also makes no sense since the SHA-1 could have been stored in many different ways.

**Comment by Jessecar96** [comment]
This doesn't seem to be needed anymore so I will close it. The indentation is also off so not merging anyways.

**Pull request closed without merging**
