### PR TITLE
Update packages and remove compile warnings.

### LINKED ISSUE #777: SteamKit is phasing out ICallbackMsg.Handle<>
ATM SteamBot is using a non-preferred way of handling steam callbacks as the title suggests, it's the Handle<> thing. https://github.com/SteamRE/SteamKit/issues/124 states that there is another way that is preferred.  
So steambot should prepare for that.
@BlueRaja @scholtzm @FrozenHaxor @Bottswana and anyone else what you think?

### PR DESCRIPTION
**Pull request by WildCard65**
Closes #777
Also updates packages.

### CODE REVIEW

**Comment by WildCard65** [comment]
I didn't test this but I shouldn't need to as it's pretty much a straight forward switch between how SteamBot handles notifications. Basically, SteamBot was originally an steam event based bot but with a thread doing the work. Now, it depends on SteamKit doing the work of firing steam events for the bot.

**Comment by WildCard65** [comment]
Also UserHandler coders will be allowed to register their own callbacks with the bot,

**Comment by bartico6** [comment]
Nope, this does not work.
You still need the background worker to keep using (in a loop) "mgr.RunWaitCallbacks". Otherwise the bot is stuck in the 'post-doneloading' state.

**Comment by BlueRaja** [comment]
https://github.com/SteamRE/SteamKit/commit/93d323928f495f5c3c7a676cd9ac71e764442ec4#diff-45f2269fe46e3ea98c61838201e4327bR80

We still want the error-handling code, no?  It doesn't appear that the `CallbackManager` takes care of that for us.

**Comment by WildCard65** [comment]
@bartico6 how about now?
@BlueRaja I just copy+pasted everything that HandleSteamMessage had.

**Comment by bartico6** [comment]
"Da. This will work." -Heavy2k15
Yes, it will be fine this way.

**Comment by bartico6** [comment]
.. so is this getting pulled or what? :o

**Comment by ThereWasADream** [comment]
Did you use it, quake? PRs don't get merged until at least two people use
it and confirm it works.

**Comment by bartico6** [comment]
Well then I have not used this exact classfile.
I'll do it tomorrow (2AM here in Central Europe)

**Comment by ThereWasADream** [comment]
I have been using it for a day now - it looks good so far but I'd hesitate to say it's safe to merge without others confirming as well.

**Comment by WildCard65** [comment]
This pr is just to switch how steambot interacts with steam related stuff.

**Comment by ThereWasADream** [comment]
I understand that, but it is always possible to make mistakes.

**Comment by WildCard65** [comment]
This is mostly a copy+paste of code.

**Comment by ThereWasADream** [comment]
OK, well how about instead of this fruitless banter I just post the pastebin link below as a possible bug caused by this change instead. I'm having trouble interpreting it but I know I've never seen this happen prior to using this PR.

This paste is two stacks that occurred very close to one another. "Craft check" refers to a method I wrote that determines whether or not the bot needs to craft some scrap. It requires the GetInventory method in Bot.cs.

http://pastebin.com/z2akciPS

**Comment by BlueRaja** [comment]
`Unable to connect to remote server` is beyond our control, that means the Steam servers were't responding.

The important question is, after this error did the bot correctly restart?  Or did you need to shut it down and reopen the program?

**Comment by ThereWasADream** [comment]
Figures BlueRaja would see what was right in front of me. :)

I do not have any logs that indicate that the bot actually shut down. Either way, it was still running afterward.

**Comment by scholtzm** [comment]
Steam and their respective APIs were dead yesterday so that was most likely the cause.

**Comment by WildCard65** [comment]
Alright, PR updated for newest steamkit binary

**Comment by ThereWasADream** [comment]
This line is causing an issue:

CallbackManager = subscriptions.Add(CallbackManager.Subscribe(SteamClient);

This line is missing a ')' after SteamClient. That's easy, but from there I can't figure out how to fix it because I am not a pro.

Compiler complains of CS0029 (implicit type conversion) for void/CallbackManager and SteamClient/Action<?>.

Take a look and see what you can do. :)

**Comment by WildCard65** [comment]
That line wasn't suppose to change.

**Comment by WildCard65** [comment]
Fixed

**Comment by behzadpa0l** [comment]
hy guys i need tradeuserhandel for csgo items i have csgo item shop need bot for auto sent item after buy from web site Help me

**Comment by WildCard65** [comment]
Ok, I updated PR to make bot use SteamKit's smarter server list system.

**Comment by ThereWasADream** [comment]
Great job on all this quick work. Everything seems to be working very well so far, since I've gotten over my panic from the slightly differently worded Exceptions. ;-)

**Comment by WildCard65** [comment]
Does the serverlist saving/loading work?

**Comment by ThereWasADream** [comment]
I'm going to humble myself lol...how could I verify that for you? I saw in Bot.cs where that is done but to me it only looked like it did so when the bot was started and stopped, and I never do that manually.

**Comment by WildCard65** [comment]
I'm asking if the bot is able to deserialize the servers.json file properly and is saving it properly.

**Comment by ThereWasADream** [comment]
I am probably not the right person to ask. I searched Steambot-master for such a file. Either I don't know enough to understand what you're asking, or it is not saving anywhere in the folders containing Steambot.

**Comment by WildCard65** [comment]
Nvm, I'll try to get @bartico6 to test.

**Comment by WildCard65** [comment]
Ok, I think PR is ready to be merged.

**Comment by ThereWasADream** [comment]
You're a pro! Just one question - I don't think this is supposed to happen: http://pastebin.com/Ke1nKLQA

It's possible I goofed on the copy-paste, but I really don't think so.

**Comment by BlueRaja** [comment]
Narth, you should not be copying/pasting code.  That is exactly what `git` is for.  I recommend you download SourceTree and read a tutorial on how source control using git works.

**Comment by WildCard65** [comment]
@BlueRaja Ever going to review this?

**Comment by WildCard65** [comment]
This thing has a typo in it, I'll eventually fix that.

**Comment by WildCard65** [comment]
Typo fixed

**Comment by WildCard65** [comment]
I'll update packages for steamkit 1.6.5 later

**Comment by WildCard65** [comment]
Going to remake this PR

**Pull request closed without merging**
