### PR TITLE
Back to VS2010 Patch

### PR DESCRIPTION
**Pull request by gabrielmtzcarrillo**

### CODE REVIEW

**Comment by WildCard65** [comment]
And why not install VS 2013 free edition?

**Comment by Bottswana** [comment]
We should probably cover more than just the lastest version of VS if possible in my opinion.
If this dosen't affect the codebase and makes the source more accessible then its probably fine.

**Comment by WildCard65** [comment]
Ya but VS2013 is newer and .net45 has things like the await keyword latest ubuntu ships with mono that is capable of .net45.

**Comment by WildCard65** [comment]
Another thing, Xamarin Studios supports the vs 2013 solution format.

**Comment by gabrielmtzcarrillo** [comment]
@WildCard65 so, are you telling me that it's easier to download and install vs2013 (which requires in my case install windows 8) instead of patching 3 files with notepad? -anyway I proposed this by request-

**Comment by Bottswana** [comment]
Personally I'm for this given that we aren't taking advantage of N4.5 yet.

**Comment by WildCard65** [comment]
@gabrielmtzcarrillo are you on Windows 7?
@Bottswana SteamKit2 issue I linked area may take advantage of .net 4.5 also Windows XP is no longer getting security patches so I assume people would eventually save up to switch to Windows 7

**Comment by WildCard65** [comment]
Another thing, once the steamweb pr is merge I want to go through and make use of all the awaitable methods.

**Comment by BlueRaja** [comment]
The `await` PR has been closed without merging, but I still don't think we should merge this.  Now that the free edition of VS 2013 supports addons, and Mono supports .Net 4.5, there is really no reason not to upgrade.

**Comment by Bottswana** [comment]
If we plan to use N4.5, then we can close this without merging.

**Comment by WildCard65** [comment]
I'm for closing this also seeing as #705 is open

**Pull request closed without merging**
