### PR TITLE
Update to new schema API

### PR DESCRIPTION
**Pull request by kilpkonn**
Old api is not working any more. Everything should work with combination of these 2 new apis.

Some more info: https://github.com/Jessecar96/SteamBot/issues/1126

### CODE REVIEW

**Comment by greggameplayer** [comment]
good implementation this should be merged quickly in order to be able to reuse SteamBot

**Comment by BlueRaja** [comment]
Code LGTM.  Has anyone tested it to make sure it works?

**Comment by greggameplayer** [comment]
@BlueRaja i've tested in it's work but there is some respond problem somewhere else when the bot have to accept the real time trade

**Comment by nightfuryninja** [comment]
Thank you so much!

**Pull request merged**
