### PR TITLE
TradeOffer.Accept changes

### PR DESCRIPTION
**Pull request by MadBender**
Hi
I use your SteamBot for my custom bot aplication and it helps me a lot. Thank you for developing this project
Here are some changes that I had to make. Please review them and merge to master if they are good

1. I added an optional parameter to SteamWeb.Fetch and Request method that allows them to parse even non-200 HTTP responses (for example, when the trade can't be accepted, the error message is returned in HTTP 500 response, the original function throws WebException and can't get that message). 
This does not break API and preserves original function behavior for existing clients
2. TradeOffer.Accept now returns TradeOfferAcceptResponse which contains success flag, trade ID and error message. This function uses new SteamWeb.Fetch behavior to get error message. Also this is a breaking change, so clients may need to fix their code a bit.

### CODE REVIEW

**Comment by geel9** [comment]
Why not have TradeOfferAcceptResponse implicitly convert to a boolean to avoid breaking existing implementations?

**Comment by MadBender** [comment]
I think, implicit conversion of object to bool will look weird and non-obvious. And I also removed the output parameter (tradeId), it is now returned as one of result's field.
The change is actually small and can be made easily

**Comment by BlueRaja** [comment]
I agree with @geel9.  If there's an easy way to keep backwards-compatibility, we should be doing it.

**Comment by MadBender** [comment]
Will it be okay if I make a function with old signature and mark it as obsolete?

**Comment by BlueRaja** [comment]
@MadBender Do you plan on cleaning up this PR, or should it be closed?

**Comment by MadBender** [comment]
Oh, forgot about this one.
I'll look into it later this week

**Comment by MadBender** [comment]
Added old signature for TradeOffer.Accept

**Comment by BlueRaja** [comment]
@MadBender Could you update this to resolve the conflicts?

**Comment by MadBender** [comment]
updated

**Comment by BlueRaja** [comment]
Recrated this PR in #933

**Pull request merged**
