### PR TITLE
Refactored and formatted ExampleBot

### PR DESCRIPTION
**Pull request by WildCard65**
This cleans up a bit of ExampleBot project.
Replaces #784
SteamTrade will be done in a seperate PR.
Let me know if I missed anything.

### CODE REVIEW

**Comment by ThereWasADream** [comment]
You didn't include #778, and so this PR won't compile with it. You'd need to redo one or both of them for it to merge automatically - I know, because I actually used git this time and wouldn't merge. I did the work of combining them manually. There's some extra junk in my bot.cs (just control+F "int retries" and you'll see the only additions beyond the master and these PRs) but it combines #778 and #784 and compiles fine...it's been working all day. Here's a pastebin of my bot.cs:

http://pastebin.com/yQ9NXTh7

Someone else who likes using git can pull it, I guess.

Configuration.cs is also missing two lines from #778 that are needed:

[JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate)]
[DefaultValue(0)]
public int CellID { get; set; }

**Comment by WildCard65** [comment]
I'll do the merge thing when we get there.

**Comment by WildCard65** [comment]
It's generally not recommended to have PRs depend on another PR unless there isn't a choice.

**Comment by BlueRaja** [comment]
> It's generally not recommended to have PRs depend on another PR unless there isn't a choice.
That's fine if the PR touches a lot of files _(like this one)_ and is sure to be merged soon.  However, you _shouldn't_ mix a huge formatting PR with other changes.  Just [look at how huge this PR is](https://github.com/Jessecar96/SteamBot/pull/789/files?w=1) even without the whitespace changes.  There is no possible way I can code-review this.

**Comment by WildCard65** [comment]
Very well, I'll have to do the splitting of this PR tomorrow then.

**Pull request closed without merging**
