### PR TITLE
Poll trade offer status automatically

### PR DESCRIPTION
**Pull request by BlueRaja**
Changes suggested in #914 

I've been testing for a few days, and it seems to work fine.  Anyone care to test?  You no longer need to call `TradeOfferManager.GetOffers()`, it's done automatically.  You just need to handle `UserHandler.OnTradeOfferUpdated()`

### CODE REVIEW

**Comment by BlueRaja** [comment]
Er, AppVeyor is failing.  It doesn't seem to like my C# 6 syntax.  Are we not using that yet?  We're compiling against .Net 4.5....

**Comment by BlueRaja** [comment]
Alright, I've updated to remove the C# 6 syntax so AppVeyor stops complaining.

I've also been testing it for the last week, and it works fantastic!  Has anyone else had a chance to look at it yet?

**Comment by ThereWasADream** [comment]
I was considering trying to fix it for NET 4.5 and using it to help out, but I quickly discovered that it was...over my head. Thanks for doing that. I will try it and let you know...unless I forget! Oops!

**Comment by ThereWasADream** [comment]
So far, this works really well for mobile confirmations when you have the method to accept mobile confirmations called in response to TradeOfferStateNeedsConfirmation.

One thing, I'm not sure if this is supposed to be obvious or an actual oversight (I am a scrub), but for those like me who wouldn't immediately see this issue, when you update your code without modifying any cutoff dates/times, TradeOfferStateAccepted will be called for just about every trade in your history. So, if you put _anything_ in the case TradeOfferStateAccepted as shown in the example on SimpleUserHandler, it will be called like a billion times. Fair warning! I annoyed a lot of people!

**Comment by BlueRaja** [comment]
@ThereWasADream Yes that is intentional, there's nothing we can do about that without keeping track of which trades we've already accepted somewhere _(which would require some sort of database)_.  I tried to make it very clear that each userhandler needs to keep track on its own which trades it has already accepted.  That is part of the reason why it's a single `OnTradeOfferUpdated` method, and not a `OnTradeOfferAccepted` method.

**Comment by ThereWasADream** [comment]
I'm sure it would be clear to anyone else except me. I usually figure these things out _eventually_ but I figured it would be better to say something and find out it was an oversight by me than miss out on a potential bug report. So basically there's nothing wrong here.

**Comment by BlueRaja** [comment]
Awesome!  Anyone else wanna take a look, or should I just merge?

**Comment by waylaidwanderer** [comment]
I can't look at your code right now, but are you polling using the current timestamp with GetTradeOffers? That should solve the issue of calling stuff like OnTradeAccepted twice, even after restarts. I'm pretty sure this isn't an issue with SteamTradeOffersBot.

**Comment by BlueRaja** [comment]
@waylaidwanderer What do you mean "the current timestamp"?  The value sent to the server needs to be set to _"the last time we requested trade offers from the server"_, which there is no way of knowing if the bot just started up, unless we store it somewhere.

If you are setting it to the current timestamp when the bot starts up, that means any trade offers sent between when the bot last went offline and now will be missed.

**Comment by BlueRaja** [comment]
Er, there's been no discussion for a month, I think I will merge this, it seems like a pretty basic need for everyone.

**Pull request merged**
