### PR TITLE
ItemAdded/Removed events published twice

### PR DESCRIPTION
**Pull request by BlueRaja**
Fix for #716.
My bot is currently down because of #708, so I have no way of testing.  Could someone test this for me?  Be super-careful, since this is completely untested code...

### CODE REVIEW

**Comment by scholtzm** [comment]
I have tested this and it seems to be correct. I'm unable to replicate the old buggy behavior. @FrozenHaxor can you try this out?

**Comment by FrozenHaxor** [comment]
@scholtzm Honestly I cannot get this bug to happen, I'd rather not mess up my production bots while everything is fine as is..

**Comment by Bottswana** [comment]
I don't use these events much nor are my bots live from the email changes,
so can't help test either

**Comment by Obilux** [comment]
@BlueRaja I tried this and this worked perfectly.

**Pull request merged**
