### PR TITLE
Renamed TF2Value in comments also

### PR DESCRIPTION
**Pull request by BlueRaja**
The previous merge missed some comments.  @WildCard65, if you use [Resharper](https://www.jetbrains.com/resharper/) it will find changes in comments/strings as well when renaming things.  It's free for students.

Since this is only a change to comments/strings, I will merge this immediately if the CI-build passes.

### CODE REVIEW

**Comment by scholtzm** [comment]
VS does this out of the box as well.

And you forgot about the file name :smile: `Tf2Value.cs`

**Comment by BlueRaja** [comment]
The file name has been changed already.  Github is displaying it incorrectly.

**Comment by scholtzm** [comment]
Actually, it might be a [git thing](http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git).
I remember running into this a while ago.

**Comment by WildCard65** [comment]
Actually, looking at my local repo copy, I think the file name isn't changed. Which explains y the ci passed b4 my "Forgot some saves" commit

**Pull request merged**
